---
# Configuration file for MegaLinter
# See all available variables at
# https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all
SHOW_ELAPSED_TIME: false
PARALLEL: true
VALIDATE_ALL_CODEBASE: true
FILEIO_REPORTER: false
GITHUB_STATUS_REPORTER: true
IGNORE_GENERATED_FILES: true
PRINT_ALPACA: false
SARIF_REPORTER: true
SHOW_SKIPPED_LINTERS: false
GO_REVIVE_CLI_LINT_MODE: "project"

DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
  - REPOSITORY_TRIVY
  - REPOSITORY_TRIVY_SBOM
  - REPOSITORY_TRUFFLEHOG
  - REPOSITORY_CHECKOV
  - REPOSITORY_KICS
  - REPOSITORY_GRYPE
  - SPELL_CSPELL
  - SPELL_MISSPELL
  - COPYPASTE_JSCPD

ENABLE_LINTERS:
  - GO_GOLANGCI_LINT
  - GO_REVIVE
  - YAML_YAMLLINT
  - MARKDOWN_MARKDOWNLINT
  - JSON_JSONLINT
  - BASH_SHELLCHECK
  - BASH_SHFMT
  - DOCKERFILE_HADOLINT
  - ACTION_ACTIONLINT

MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.json

FILTER_REGEX_EXCLUDE: (testdata|\.git)
