---
extends: relaxed

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

ignore-from-file: .gitignore

rules:
  empty-lines:
    max: 1
    max-start: 0
    max-end: 1

  line-length:
    max: 100
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: false
