name: 'Go Test to SARIF Converter'
description: 'Converts Go test JSON output to SARIF format.'

author: 'Ismo Vuorinen'
branding:
  icon: "check"
  color: "green"

inputs:
  input_file:
    description: 'Path to the Go test JSON results file.'
    required: true
  output_file:
    description: 'Path where the SARIF output should be saved.'
    required: true

runs:
  using: "docker"
  image: "docker://ivuorinen/go-test-sarif-action:v1"
  with:
    input_file: ${{ inputs.input_file }}
    output_file: ${{ inputs.output_file }}
