---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: PR Lint

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

permissions:
  contents: read

jobs:
  Linter:
    name: PR Lint
    runs-on: ubuntu-latest
    permissions:
      contents: write # only for delete-branch option
      issues: write
      pull-requests: write
      statuses: write

    steps:
      - uses: ivuorinen/actions/pr-lint@6e8f2aae9d0846d901d9eba15b8e94a2900573dc # v2026.03.02
