---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release new action version

on:
  release:
    types: [released]

env:
  TAG_NAME: ${{ github.event.release.tag_name }}

permissions: read-all

jobs:
  update_tag:
    name: Update the major tag to include the ${{ env.TAG_NAME }} changes
    environment:
      name: releaseNewActionVersion
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update the ${{ env.TAG_NAME }} tag
        uses: actions/publish-action@f784495ce78a41bac4ed7e34a73f0034015764bb # v0.3.0
        with:
          source-tag: ${{ env.TAG_NAME }}
